# Generated by Django 6.0.4 on 2026-04-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_dailytimerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
